server:
  port: 8888

app:
  host: http://localhost
  api-prefix: /delivery
  uri:
    identity-service: http://localhost:8081
    notification-service: http://localhost:8084
  whitelist:
    - /api/v1/hello
    - /api/v1/auth/login
    - /api/v1/auth/refresh-token
    - /api/v1/auth/check-before-register
    - /api/v1/auth/register
    - /api/v1/auth/login-google-mobile
    - /api/v1/auth/login-google-web
    - /api/v1/auth/response-login-google-web
    - /api/v1/auth/facebook
    - /api/v1/auth/verify
    - /api/v1/auth/verify-resent
    - /api/v1/auth/password/forgot
    - /api/v1/auth/password/reset
    - /api/v1/auth/password/change-password
  filter-order:
    security: -2
    authentication: -1
spring:
  application:
    name: spring-api-gateway
  cloud:
    gateway:
      globalcors:
        cors-configurations:
          '[/**]':
            allowedOrigins:
              - ${app.host}:8082
              - ${app.host}:8088
              - ${app.host}:8090
              - ${app.host}:8090
            allowedMethods:
              - GET
              - POST
              - PUT
              - DELETE
              - OPTIONS
            allowedHeaders:
              - Authorization
              - Content-Type
              - Accept
              - Origin
              - X-Requested-With
            exposedHeaders:
              - "Authorization"
            allowCredentials: true
            maxAge: 3600
      routes:
        # Identity Service
        - id: identify_service
          uri: ${app.uri.identity-service}
          predicates:
            - Path=${app.api-prefix}/identity/public/**
          filters:
            - StripPrefix=2
        # Notification Service
        - id: notification_service
          uri: ${app.uri.notification-service}
          predicates:
            - Path=${app.api-prefix}/notification/public/**
          filters:
            - StripPrefix=2