server:
  port: 8888
  servlet:
    context-path: ${app.api-prefix}
app:
  api-prefix: /delivery
  host: http://localhost
  uri:
    identity-service: http://localhost:8081
    notification-service: http://localhost:8084
    product-service: http://localhost:8085
    rating-service: http://localhost:8086
  whitelist:
    #    Identity endpoint public
    - ${app.api-prefix}/identity/public/api/v1/auth/login
    - ${app.api-prefix}/identity/public/api/v1/auth/check-before-register
    - ${app.api-prefix}/identity/public/api/v1/auth/register
    - ${app.api-prefix}/identity/public/api/v1/auth/account
    - ${app.api-prefix}/identity/public/api/v1/auth/refresh-token
    - ${app.api-prefix}/identity/public/api/v1/auth/login-google-mobile
    - ${app.api-prefix}/identity/public/api/v1/auth/login-google-web
    - ${app.api-prefix}/identity/public/api/v1/auth/password/forgot
    - ${app.api-prefix}/identity/public/api/v1/auth/password/reset

    #    Product endpoint public
    - ${app.api-prefix}/product/public/api/v1/product
    - ${app.api-prefix}/product/public/api/v1/product/{id}
    - ${app.api-prefix}/product/public/api/v1/product/category/{id}
    - ${app.api-prefix}/product/public/api/v1/product-option/{id}
    - ${app.api-prefix}/product/public/api/v1/category
    - ${app.api-prefix}/product/public/api/v1/category/{id}

    #    Rating endpoint public
    - ${app.api-prefix}/rating/public/api/v1/review/product/pageable/{id}

    - /swagger/**/swagger-ui.html
    - /api-docs/**
  filter-order:
    security: -2
    authentication: -1
spring:
  application:
    name: spring-api-gateway
  cloud:
    gateway:
      globalcors:
        cors-configurations:
          '[/**]':
            allowedOrigins:
              - ${app.host}:8082
              - ${app.host}:8088
              - ${app.host}:8090
              - ${app.host}:8090
            allowedMethods:
              - GET
              - POST
              - PUT
              - DELETE
              - OPTIONS
            allowedHeaders:
              - Authorization
              - Content-Type
              - Accept
              - Origin
              - X-Requested-With
            exposedHeaders:
              - "Authorization"
            allowCredentials: true
            maxAge: 3600
      routes:
        # Identity Service
        - id: identify_service
          uri: ${app.uri.identity-service}
          predicates:
            - Path=${app.api-prefix}/identity/public/**
          filters:
            - StripPrefix=3

        # Notification Service
        - id: notification_service
          uri: ${app.uri.notification-service}
          predicates:
            - Path=${app.api-prefix}/notification/public/**
          filters:
            - StripPrefix=3

        # Product Service
        - id: product_service
          uri: ${app.uri.product-service}
          predicates:
            - Path=${app.api-prefix}/product/public/**
          filters:
            - StripPrefix=3

        # Rating Service
        - id: rating_service
          uri: ${app.uri.rating-service}
          predicates:
            - Path=${app.api-prefix}/rating/public/**
          filters:
            - StripPrefix=3

        # Swagger documentation
        ## Identity service
        - id: identity-swagger-ui
          uri: ${app.uri.identity-service}
          predicates:
            - Path=/swagger/identity/swagger-ui.html
          filters:
            - RewritePath=/swagger/identity/swagger-ui.html, /swagger-ui.html
        - id: identity-api-docs
          uri: ${app.uri.identity-service}
          predicates:
            - Path=/api-docs/identity
          filters:
            - RewritePath=/api-docs/identity, /v3/api-docs
