server:
  port: 8081
spring:
  jackson:
    time-zone: Asia/Ho_Chi_Minh
  main:
    allow-bean-definition-overriding: true
  profiles:
    active: ${SPRING_PROFILES_ACTIVE:dev}
  application:
    name: android-delivery-back-end
  datasource:
    url: jdbc:mysql://${MYSQL_HOST:localhost}:${MYSQL_PORT:3306}/${MYSQL_DATABASE:delivery}
    username: ${MYSQL_USER:root}
    driver-class-name: com.mysql.cj.jdbc.Driver
  data:
    redis:
      host: ${REDIS_HOST}
      port: ${REDIS_PORT}
    mongodb:
      database: ${MONGODB_DATABASE}
      uri: ${MONGODB_URI}
  jpa:
    hibernate:
      ddl-auto: none
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQLDialect
  security:
    allowed:
      origins:
        - ${app.host}:8082
        - ${app.host}:8088
        - ${app.host}:8090
        - ${app.host}:8090
      methods:
        - GET
        - POST
        - PUT
        - DELETE
        - OPTIONS
      headers:
        - Authorization
        - Content-Type
        - Accept
        - Origin
        - X-Requested-With
    oauth2:
      client:
        registration:
          google:
            client-id: 897537541683-7ikcdbpl9c00tfcgbtu10dfu8si2gav4.apps.googleusercontent.com
            client-secret: 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
            scope: openid, profile, email
            redirect-uri: "{baseUrl}/login/oauth2/code/google"
            authorization-grant-type: authorization_code
        provider:
          google:
            authorization-uri: https://accounts.google.com/o/oauth2/v2/auth
            token-uri: https://oauth2.googleapis.com/token
            user-info-uri: https://www.googleapis.com/oauth2/v3/userinfo

jwt:
  base64-secret: 1KYM6Qp2S8084HQLp+weSBZkZLhs73NkTMoJeql5Gxc7iSUHP/xEtT719zB6XQMilF2R89alaiX8PQl6VXfAhQ==
  access-token-validity-in-seconds: 30
  refresh-token-validity-in-seconds: 50

app:
  whitelist:
    - /api/v1/auth/login
    - /api/v1/auth/check-before-register
    - /api/v1/auth/register-email
    - /api/v1/auth/register
    - /api/v1/auth/account
    - /api/v1/auth/refresh-token
    - /api/v1/auth/login-google-mobile
    - /api/v1/auth/login-google-web
    - /api/v1/auth/password/forgot
    - /api/v1/auth/password/reset
    - /v3/api-docs
    - /v3/api-docs/**
    - /swagger-ui/**
    - /oauth2/**
    - /auth/**
    - /auth/google
    - /api/v1/product/**
    - /api/v1/category/**
    - /api/v1/health/**
  cookie:
    key:
      refreshToken: refresh_token
    defaultValue:
      refreshToken: empty
  host: ${HOST:localhost}
  otp:
    length: 6
    expiration: 600000
    max-try: 5
    resend:
      expiration: 1440000
      max-try: 3
  paging:
    size: 10
  database:
    entry:
      product-review:
        limit: 10
