spring:
  datasource:
    password: root
  data:
    redis:
      host: ${REDIS_HOST:localhost}
      port: ${REDIS_PORT:6379}
  security:
    allowed:
      origins:
        - ${app.localhost}:8082
        - ${app.localhost}:8088
        - ${app.localhost}:8090
        - ${app.localhost}:8090
app:
  cookie:
    key:
      refreshToken: refresh_token
    defaultValue:
      refreshToken: empty
  localhost: http://localhost
