spring:
  datasource:
    url: jdbc:mysql://localhost:3306/delivery_rating
    username: root
    password: 123
#  rabbitmq:
#    host: localhost
#    port: 5672
#    username: admin
#    password: 123
#    virtual-host: core
#    queue:
#      name: rating-queue
#      exchange: rating-exchange
#      routing-key: rating-key