server:
  port: 8087
spring:
  application:
    name: file-service
  profiles:
    active: ${SPRING_PROFILES_ACTIVE:dev}
  data:
    mongodb:
      host: ${MONGODB_HOST}
      port: ${MONGODB_PORT}
      database: ${MONGODB_DATABASE}

app:
  service:
    firebase:
      bucket: delivery-react-native-ap-fa468.appspot.com