# product_service

###
# group: category
# @name get all
GET http://localhost:8085/api/v1/category

###
# group: category
# @name get by id
GET http://localhost:8085/api/v1/category/66d31b1443a67fd67b714c97

###
# group: category
# @name create
POST http://localhost:8085/api/v1/category
Content-Type: application/json

{
  "name": "burger"
}

###
# group: option
# @name get all
GET http://localhost:8085/api/v1/product-option

###
# group: option
# @name get option by id
GET http://localhost:8085/api/v1/product-option/66d31af443a67fd67b714c90

###
# group: option
# @name get group option by id
GET http://localhost:8085/api/v1/product-option/66d31b0a43a67fd67b714c93

###
# group: option
# @name create option
POST http://localhost:8085/api/v1/product-option
Content-Type: application/json

{
  "name": "chicken",
  "price": 20000
}

###
# group: option
# @name create group option
POST http://localhost:8085/api/v1/product-option
Content-Type: application/json

{
  "name": "meat",
  "options": [
    {
      "name": "pig",
      "price": 30000
    }
  ]
}

###
# group: product
# @name get all
GET http://localhost:8085/api/v1/product?
    page=1

###
# group: product
# @name get by id
GET http://localhost:8085/api/v1/product/66d31ce03d76c79dc1ee4847

###
# group: product
# @name get by category
GET http://localhost:8085/api/v1/product/category/66d31b1443a67fd67b714c97

###
# group: product
# @name remove discount
DELETE http://localhost:8085/api/v1/product/discount/66d31ce03d76c79dc1ee4847

###
# group: product
# @name create
POST http://localhost:8085/api/v1/product
Content-Type: application/json

{
  "name": "Chicken Burger 2",
  "price": 30000000,
  "quantity": 100,
  "description": "A delicious chicken burger served on a toasted bun with fresh lettuce, tomato slices, and mayonnaise. Juicy grilled chicken patty seasoned to perfection for a mouthwatering taste experience.",
  "category": "66d31b1443a67fd67b714c97",
  "options": [
    "66d31af443a67fd67b714c90",
    "66d31b0a43a67fd67b714c93"
  ],
  "nutritional": [
    {
      "name": "Calories",
      "value": 420,
      "unit": "g"
    },
    {
      "name": "Protein",
      "value": 27,
      "unit": "g"
    },
    {
      "name": "Carbs",
      "value": 30,
      "unit": "g"
    },
    {
      "name": "Fat",
      "value": 18,
      "unit": "g"
    }
  ],
  "discountInfo": {
    "discount": 60,
    "expired": "2024-08-31"
  }
}

###
# group: product
# @name set discount
PUT http://localhost:8085/api/v1/product/discount/66d31ce03d76c79dc1ee4847
Content-Type: application/json

{
  "discount": 60,
  "expired": "2024-08-31"
}

###
# group: product
# @name set image product
PUT http://localhost:8085/api/v1/product/image/66d7e4ab519664b27d636a91
Content-Type: application/json

{
  "url": "gs://delivery-react-native-ap-fa468.appspot.com/product/66d31ce03d76c79dc1ee4847/display.png"
}