# profile_service

###
# group: test
# @name create
POST {{HOST_PROFILE_SERVICE}}/{{CONTEXT_PROFILE_SERVICE}}/user/info
Content-Type: application/json

{
  "userId": 1,
  "fullName": "Lê Anh Đức",
  "birthDay": "2003-1-1",
  "gender": "FEMALE"
}

###
# group: test
# @name update
PUT {{HOST_PROFILE_SERVICE}}/{{CONTEXT_PROFILE_SERVICE}}/user/info
Content-Type: application/json

{
  "userId": 1,
  "fullName": "Lê Anh Đức",
  "birthDay": "2003-1-1",
  "gender": "FEMALE"
}

###
# group: test
# @name get one
GET {{HOST_PROFILE_SERVICE}}/{{CONTEXT_PROFILE_SERVICE}}/user/info/1

###
# group: gateway
# @name create
POST {{HOST_PROFILE_SERVICE}}/{{CONTEXT_PROFILE_SERVICE}}/user/info
Content-Type: application/json

{
  "userId": 1,
  "fullName": "Lê Anh Đức",
  "birthDay": "2003-1-1",
  "gender": "FEMALE"
}

###
# group: gateway
# @name update
PUT {{API_GATEWAY}}/{{CONTEXT_PROFILE_SERVICE}}/user/info
Content-Type: application/json

{
  "userId": 1,
  "fullName": "Lê Anh Đức",
  "birthDay": "2003-1-1",
  "gender": "FEMALE"
}

###
# group: gateway
# @name get one
GET {{API_GATEWAY}}/{{CONTEXT_PROFILE_SERVICE}}/user/info/1
Authorization: Bearer {{ACCESS_TOKEN}}