# rating_service

###
# @name get pageable rating by product id
GET http://localhost:8086/api/v1/review/product/pageable/1?
    rating=4

###
# @name get review overall by product id
GET http://localhost:8086/api/v1/review/product/1

###
# @name get review overall (not analyze) list product
GET http://localhost:8086/api/v1/review/product?
    product_id[]=2